# https://facelessuser.github.io/pyspelling/configuration/
matrix:
- name: Markdown
  aspell:
    lang: fr
    d: fr_FR
  dictionary:
    encoding: utf-8
    wordlists:
    - .ignoredWords.txt
  pipeline:
  - pyspelling.filters.markdown:
  sources:
  - '**/*.md'
  default_encoding: utf-8